name: elesson
description: Elesson - Plataforma Digital de Ensino Personalizado

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.16

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  shimmer_animation: ^2.1.0
  cupertino_icons: ^1.0.5
  url_launcher: ^6.0.10
  provider: ^6.0.5
  permission_handler: ^10.4.3
  dio: ^5.3.2
  fdottedline_nullsafety: ^2.0.1
  flutter_audio_recorder2: ^0.0.2
  avatar_glow: ^2.0.2
  speech_to_text: ^6.3.0
  http: ^1.1.0
  image_picker: ^1.0.1
  shared_preferences: ^2.0.7
  percent_indicator: ^4.2.1
  googleapis_auth: any
  googleapis: ^11.3.0
  cached_network_image: ^3.2.0
  screen_loader: ^4.0.1
  connectivity_plus: ^4.0.2
  dartz: ^0.10.1
  pretty_dio_logger: ^1.2.0-beta-1
  brasil_fields:
  equatable: ^2.0.5
  flutter_spinkit: ^5.2.0
  wakelock:
  url_strategy: ^0.2.0
  qr_code_scanner: ^1.0.1
  soundpool: ^2.4.0
  auto_size_text: ^3.0.0
  firebase_core: ^2.20.0
  firebase_crashlytics: ^3.5.7
  flutter_native_splash: ^2.3.5
  just_audio: ^0.9.21
  flutter_secure_storage: ^9.2.2
  sembast: ^3.7.1
  lottie: ^3.1.2

dev_dependencies:
  change_app_package_name: ^1.1.0
  flutter_launcher_icons: ^0.13.1

  flutter_test:
    sdk: flutter

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/playstore.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/icons/playstore.png"
    background_color: "#000000"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/icons/playstore.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/icons/playstore.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/img/
    - assets/fonts/
    - assets/icons/
    - assets/animations/
    - assets/audio/
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: ElessonIconLib
      fonts:
        - asset: assets/fonts/ElessonIconLib.ttf

    - family: Mulish
      fonts:
        - asset: assets/fonts/Mulish-Black.ttf
          weight: 900
        - asset: assets/fonts/Mulish-Regular.ttf

    - family: Comic
      fonts:
        - asset: assets/fonts/ComicNeue-Bold.ttf
          weight: 900
        - asset: assets/fonts/ComicNeue-Regular.ttf
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
