/// Flutter icons ElessonIconLib
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  ElessonIconLib
///      fonts:
///       - asset: fonts/ElessonIconLib.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class ElessonIconLib {
  ElessonIconLib._();

  static const _kFontFam = 'ElessonIconLib';
  static const dynamic _kFontPkg = null;

  static const IconData undo = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData voice = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData camera = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chevron_down = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chevron_left = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chevron_right = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chevron_up = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData close = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData settings = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
